- hosts: localhost
  gather_facts: no
  tasks:
  - name: install pip3
    apt: 
      name: pip3
      state: present

  - name:
    pip:
      name: boto3
      state: present

  - name: Creating Security Group for WebServer on AWS
    ec2_group:
      name: WebSG
      description: Security Group for Web Server allowing port for http and ssh
      region: ap-south-1
        #    aws_access_key: "{{ access_key }}"
        #      aws_secret_key: "{{ secret_key }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 172.92.243.181/32
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 65.97.82.0/24
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0

- name: launching ec2 instance for webserver
    ec2:
      key_name: nv-ansible-key
      instance_type: t2.micro
      image: ami-077053fb4029de92f
      wait: true
      group: WebSG
      count: 1
      vpc_id: vpc-0bc2284e05e08bf28
      #vpc_subnet_id: subnet-6dfdc705
      assign_public_ip: yes
      region: ap-south-1
      state: present
#     aws_access_key: "{{ access_key }}"
#     aws_secret_key: "{{ secret_key }}"
      instance_tags:
        Name: webserver
    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: webserver
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      state: started
    loop: "{{ ec2.instances }}"

- hosts: webserver
  gather_facts: no
  tasks:
  - name: running role
    include_role:
      name: httpdserver
